version: '3.7'
services:
  common-hosting:
    image: ctheory/common-hosting-server:latest
    deploy:
      replicas: 0

  ipfs:
    image: ctheory/alpine-ipfs:v0.4.18
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.05'
          memory: 256M
    volumes:
      - "/mnt/volume2/ipfs:/root/.ipfs"

  cidhookd:
    image: jchancehud/cidhookd:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.05'
          memory: 128M
    secrets:
      - cidhook_secret
    environment:
      - CIDHOOK_SECRET_PATH=/run/secrets/cidhook_secret

  dnslink-cid-badge:
    image: ctheory/dnslink-cid-badge:latest
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.05'
          memory: 64M

  nginx:
    image: jchancehud/alpine-nginx:latest
    depends_on:
      - ipfs
      - rinkeby
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '0.05'
          memory: 128M
    secrets:
      - commontheory_cert.pem
      - commontheory_privkey.pem
      - commontheory_fullchain.pem
    environment:
      - CONFIG_URL=https://raw.githubusercontent.com/common-theory/blueprint/master/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

  rinkeby:
    image: ethereum/client-go:latest
    command: --rinkeby --datadir=/data --rpc --rpcaddr 0.0.0.0 --rpcvhosts "*" --rpccorsdomain "*"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.rinkeby == 1
      resources:
        reservations:
          memory: 1024M
    volumes:
      - "/mnt/volume2/rinkeby:/data"

  homestead:
    image: ethereum/client-go:latest
    command: --datadir=/data --rpc --rpcaddr 0.0.0.0 --rpcvhosts "*" --rpccorsdomain "*"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.homestead == 1
      resources:
        reservations:
          memory: 1024M
    volumes:
      - "/mnt/volume2/homestead:/data"

secrets:
  commontheory_cert.pem:
    external: true
  commontheory_privkey.pem:
    external: true
  commontheory_fullchain.pem:
    external: true
  eosio_key:
    external: true
  cidhook_secret:
    external: true
