version: '3.7'
services:
  commontheoryio:
    image: ctheory/static-server:latest
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
      - "80:3000"
      - "443:3001"
    secrets:
      - commontheory_cert.pem
      - commontheory_privkey.pem
      - commontheory_fullchain.pem
    environment:
      ENABLE_HTTPS: 'true'
      HTTPS_CERT: /run/secrets/commontheory_cert.pem
      HTTPS_PRIVATE_KEY: /run/secrets/commontheory_privkey.pem
      HTTPS_CERT_CA: /run/secrets/commontheory_fullchain.pem
      REDIRECT_HTTPS: 'true'
  mainnet:
    image: ctheory/eos-mainnet:latest
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '0.51'
          memory: 1024M
    ports:
      - "4321:4321"
      - "8888:8888"
      - "9876:9876"
    volumes:
      - "/mnt/volume1/mainnet:/data"
# TODO: Generate genesis block, create docker image, then implement here
  testnet:
    image: eosio/eos:v1.2.5
    deploy:
      mode: replicated
      replicas: 0
      placement:
        constraints:
          - node.role != manager
secrets:
  commontheory_cert.pem:
    external: true
  commontheory_privkey.pem:
    external: true
  commontheory_fullchain.pem:
    external: true
