version: '3.7'
services:
  ipfs:
    image: ctheory/alpine-ipfs:v0.4.17
    deploy:
      endpoint_mode: dnsrr
      replicas: 3
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  pinned-ipfs:
    image: ctheory/alpine-ipfs:v0.4.17
    environment:
      - CIDS_TO_PIN=/ipns/blockchains.ctheory.io
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
      placement:
        constraints:
          - node.role != manager
          - node.labels.volume1 == 1
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    ports:
      - target: 4001
        published: 4001
        protocol: tcp
        mode: host

  nginx:
    image: ctheory/alpine-nginx:latest
    depends_on:
      - ipfs
      - swarmpit-app
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
    secrets:
      - commontheory_cert.pem
      - commontheory_privkey.pem
      - commontheory_fullchain.pem
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - common

  rinkeby:
    image: ethereum/client-go:latest
    command: --rinkeby --datadir=/data --rpc --rpcaddr 0.0.0.0 --rpcvhosts "*" --rpccorsdomain "*"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.network == rinkeby
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
    volumes:
      - "/mnt/volume1/rinkeby:/data"

networks:
  common:
    external:
      name: common

secrets:
  commontheory_cert.pem:
    external: true
  commontheory_privkey.pem:
    external: true
  commontheory_fullchain.pem:
    external: true
  commontheory_key:
    external: true
  eosio_key:
    external: true

volumes:
  db-data:
