version: '3.7'
services:
  common-hosting:
    image: ctheory/common-hosting-server:latest
    deploy:
      replicas: 0

  ipfs:
    image: ctheory/alpine-ipfs:v0.4.17
    deploy:
      endpoint_mode: dnsrr
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  nginx:
    image: ctheory/alpine-nginx:latest
    depends_on:
      - ipfs
      - rinkeby
      - homestead
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role != manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
    secrets:
      - commontheory_cert.pem
      - commontheory_privkey.pem
      - commontheory_fullchain.pem
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress

  rinkeby:
    image: ethereum/client-go:latest
    command: --rinkeby --datadir=/data --rpc --rpcaddr 0.0.0.0 --rpcvhosts "*" --rpccorsdomain "*"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.network == rinkeby
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
    volumes:
      - "/mnt/volume1/rinkeby:/data"

  homestead:
    image: ethereum/client-go:latest
    command: --datadir=/data --rpc --rpcaddr 0.0.0.0 --rpcvhosts "*" --rpccorsdomain "*"
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      placement:
        constraints:
          - node.labels.network == homestead
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
    volumes:
      - "/mnt/volume1/homestead:/data"

secrets:
  commontheory_cert.pem:
    external: true
  commontheory_privkey.pem:
    external: true
  commontheory_fullchain.pem:
    external: true
  commontheory_key:
    external: true
  eosio_key:
    external: true
